name: KitchenBlah
favicon: null
layout_spectrum: 0.0443488082382828
typography_spectrum: 0.6678003610577434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.18736963206902146
  lightness: 0.3326731997076422
  saturation: 0.12985619413666427
  rhythmicContrast: 0.3284005590248853
purpose: []
